lib/ombucore/urls.py
from django.urls import include, path
from django.http import JsonResponse
from ombucore.imagewidget.views import ajax_file_preview
from ombucore.admin.views import FormView
from ombucore.basicauth import basicauth_exclude

urlpatterns = [
    path('', include('ombucore.admin.urls')),
    path('', include('ombucore.auth.urls')),
    path('', include('ombucore.assets.urls')),
    path('ajax-file-preview/', ajax_file_preview, name='ajax-file-preview'),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('health-check', basicauth_exclude(lambda request: JsonResponse({"status": "ok"}))),
]

website/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cost_line_item/<int:pk>/add_note/', views.CostLineItemNotesAPI.as_view(), name='api--costlineitem--add-note'),
    path('cost_line_item/<int:pk>/update_sector_and_category/', views.CostLineItemSectorCategoryAPI.as_view(), name='api--costlineitem--edit-sector-category')
]

website/email_2fa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("two-factor-authenticate/",
         views.TwoFactorAuthenticate.as_view(),
         name="two-factor-authenticate"),

]

website/urls.py
"""website URL Configuration"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from website.admin.app_log import SendPendingNotificationsView
from website.help import views as help_views
from website.users.views import AdminLoginView, CustomPasswordResetFromKeyView
from website.views import activity
from website.views import analysis
from website.views import documents
from website.views import styleguide
from website.views.dashboard import dashboard
from website.views.duplicator import DuplicateView

urlpatterns = [
    path('', dashboard, name='dashboard'),

    # Analysis.
    path('analysis/define/', analysis.DefineCreate.as_view(), name='analysis-define-create'),
    path('analysis/<int:pk>/', analysis.AnalysisDetailView.as_view(), name='analysis'),
    path('analysis/<int:pk>/define/', analysis.DefineUpdate.as_view(), name='analysis-define-update'),
    path('analysis/<int:pk>/load-data/', analysis.LoadData.as_view(), name='analysis-load-data'),
    path('analysis/<int:pk>/assign-sector-category/', analysis.FixMissingData.as_view(), name='analysis-fix-missing-data'),
    path('analysis/<int:pk>/assign-sector-category/bulk/', analysis.FixMissingDataBulk.as_view(), name='analysis-fix-missing-data-bulk'),
    path('analysis/<int:pk>/categorize/', analysis.Categorize.as_view(), name='analysis-categorize'),
    path('analysis/<int:pk>/categorize/<int:sector_pk>/', analysis.CategorizeSector.as_view(), name='analysis-categorize-sector'),
    path('analysis/<int:pk>/categorize/<int:sector_pk>/bulk/', analysis.CategorizeSectorBulk.as_view(), name='analysis-categorize-sector-bulk'),
    path('analysis/<int:pk>/set-contribution/', analysis.SetContribution.as_view(), name='analysis-set-contribution'),
    path('analysis/<int:pk>/set-contribution/<int:sector_pk>/<str:grant>/', analysis.SetContributionSectorGrant.as_view(), name='analysis-set-contribution-sector-grant'),
    path('analysis/<int:pk>/allocate/', analysis.Allocate.as_view(), name='analysis-allocate'),
    path('analysis/<int:pk>/allocate/<int:sector_pk>/<str:grant>/', analysis.AllocateSectorGrant.as_view(), name='analysis-allocate-sector-grant'),
    path('analysis/<int:pk>/allocate/<int:sector_pk>/<str:grant>/save-suggested/', analysis.SaveSuggestedToAllConfirmView.as_view(), name='analysis-allocate-sector-grant--save-suggested'),

    path('analysis/<int:pk>/identify-output-value/', analysis.IdentifyOutputValue.as_view(), name='analysis-identify-output-value'),
    path('analysis/<int:pk>/assign-output-value/<int:sector_pk>/', analysis.AssignOutputValue.as_view(), name='analysis-assign-output-value'),
    path('analysis/<int:pk>/insights/', analysis.Insights.as_view(), name='analysis-insights'),
    path('analysis/<int:pk>/download', documents.full_cost_model_spreadsheet, name='analysis-cost-model-spreadsheet'),
    path('analysis/<int:pk>/copy', DuplicateView.as_view(), name='analysis-create-copy'),

    path('cost-line-item/<int:pk>/transactions/', analysis.CostLineItemTransactions.as_view(), name='cost-line-item-transactions'),
    path('activity/<int:pk>/', activity.ActivityInsights.as_view(), name='activity-insights'),
    path('styleguide/', styleguide.styleguidetoc, name='styleguidetoc'),
    path('styleguide/colors/', styleguide.styleguidecolors, name='styleguidecolors'),
    path('styleguide/typography/', styleguide.styleguidetypography, name='styleguidetypography'),
    path('styleguide/rte/', styleguide.styleguiderte, name='styleguiderte'),
    path('styleguide/forms/', styleguide.styleguideforms, name='styleguideforms'),
    path('styleguide/buttons-links/', styleguide.styleguidebuttons, name='styleguidebuttons'),

    path('help/', help_views.help_menu, name='help-menu'),
    path('help/<path:path>/', help_views.help_page, name='help-page'),
    path('panels/help/menu/', help_views.help_page, name='help-menu-edit'),
    path('panels/app_log/send-notifications/', SendPendingNotificationsView.as_view(), name='send-notification-subscriptions'),

    # Authentication
    re_path(r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            CustomPasswordResetFromKeyView.as_view(),
            name="account_reset_password_from_key"),
    path('accounts/', include('website.email_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/adminlogin/', AdminLoginView.as_view(), name="adminlogin"),

    # API
    path('api/', include('website.api.urls')),

    path('', include('ombucore.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('admin/', admin.site.urls),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models/account_code_description.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class AccountCodeDescription(models.Model):
    app_log_entry_link_name = "ombucore.admin:website_accountcodedescription_change"
    account_code = models.CharField(
            verbose_name=_('Account Code'),
            max_length=255,
    )
    account_description = models.CharField(
            verbose_name=_('Account Description'),
            max_length=255,
    )
    sensitive_data = models.BooleanField(
            verbose_name=_('Contains sensitive data'),
            help_text=_('When checked, costs and transactions will not be shown for this account code.'),
            default=False,
    )

    class Meta:
        verbose_name = _('Account Code Description')
        verbose_name_plural = _('Account Code Description')

    def __str__(self):
        return self.account_code

    @classmethod
    def as_map(cls):
        return {
            acd.account_code: acd
            for acd in AccountCodeDescription.objects.all()
        }

website/models/cost_line_item.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class CostLineItem(models.Model):
    analysis = models.ForeignKey(
            'website.Analysis',
            verbose_name=_('Analysis'),
            on_delete=models.CASCADE,
            related_name='cost_line_items',
    )
    country_code = models.CharField(
            verbose_name=_('Country code'),
            max_length=10,
            null=False,
            blank=True,
            default='',
    )
    grant_code = models.CharField(
            verbose_name=_('Grant code'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    budget_line_code = models.CharField(
            verbose_name=_('Budget line code'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    account_code = models.CharField(
            verbose_name=_('Account code'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    site_code = models.CharField(
            verbose_name=_('Site code'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    sector_code = models.CharField(
            verbose_name=_('Sector code'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    budget_line_description = models.CharField(
            verbose_name=_('Budget line description'),
            max_length=1000,
            null=False,
            blank=True,
            default='',
    )
    total_cost = models.DecimalField(
            verbose_name=_('Total cost'),
            max_digits=12,
            decimal_places=2,
    )
    loe_or_unit = models.DecimalField(
            verbose_name=_('LOE or Unit'),
            max_digits=12,
            decimal_places=2,
            null=True,
            blank=True,
    )
    months_or_unit = models.DecimalField(
            verbose_name=_('Months or Unit'),
            max_digits=12,
            decimal_places=2,
            null=True,
            blank=True,
    )
    unit_cost = models.DecimalField(
            verbose_name=_('Unit cost'),
            max_digits=12,
            decimal_places=2,
            null=True,
            blank=True,
    )
    dummy_field_1 = models.CharField(
            verbose_name=_('Dummy field 1'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )
    dummy_field_2 = models.CharField(
            verbose_name=_('Dummy field 2'),
            max_length=255,
            null=False,
            blank=True,
            default='',
    )

    note = models.CharField(
            verbose_name=_("Note"),
            max_length=2048,
            null=False,
            blank=True,
            default='',
    )

    cloned_from = models.ForeignKey(
            'website.CostLineItem',
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            related_name='+',
    )

    class Meta:
        verbose_name = _('Cost Line Item')
        verbose_name_plural = _('Cost Line Items')
        index_together = [
            ['country_code', 'grant_code', 'budget_line_code', 'account_code', 'site_code', 'sector_code']
        ]

    @classmethod
    def site_code_filter_choices(cls):
        return [(p, p) for p in cls.objects.order_by('site_code').values_list('site_code', flat=True).distinct() if p]

    @classmethod
    def grant_code_filter_choices(cls):
        return [(p, p) for p in cls.objects.order_by('grant_code').values_list('grant_code', flat=True).distinct() if p]


class CostLineItemConfig(models.Model):
    cost_line_item = models.OneToOneField(
            CostLineItem,
            verbose_name=_('Cost Line Item'),
            on_delete=models.CASCADE,
            related_name='config',
    )
    sector = models.ForeignKey(
            'website.Sector',
            verbose_name=_('Sector'),
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            related_name='+',
    )
    category = models.ForeignKey(
            'website.Category',
            verbose_name=_('Category'),
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            related_name='+',
    )
    allocation = models.DecimalField(
            verbose_name=_('% allocation to activity'),
            max_digits=5,
            decimal_places=2,
            null=True,
            blank=True,
    )

    output_value = models.BooleanField(
            verbose_name=_('output value'),
            default=False
    )
    cloned_from = models.ForeignKey(
            'website.CostLineItemConfig',
            on_delete=models.SET_NULL,
            null=True,
            blank=True,
            related_name='+',
    )

website/email_2fa/forms.py
from django.forms import Form, CharField
from django.utils.translation import gettext_lazy as _

from django_otp.forms import OTPAuthenticationFormMixin


class Email2FAAuthenticateForm(OTPAuthenticationFormMixin, Form):
    otp_token = CharField(label=_("Token"))

    def __init__(self, user, **kwargs):
        super().__init__(**kwargs)
        self.fields['otp_token'].widget.attrs.update({
            'autofocus': 'autofocus',
            'autocomplete': 'off',
        })
        self.user = user

    def clean(self):
        self.clean_otp(self.user)
        return self.cleaned_data

website/forms/activity.py
from django import forms
from django.utils.translation import gettext_lazy as _
from ombucore.admin.forms.base import ModelFormBase
from website.models.activity import OUTPUT_METRIC_CHOICES


class ActivityForm(ModelFormBase):
    output_metric_1 = forms.ChoiceField(
        label=_('Output Metric 1'),
        choices=OUTPUT_METRIC_CHOICES,
    )
    output_metric_2 = forms.ChoiceField(
        label=_('Output Metric 2'),
        choices=[('', _('(Choose)'))] + OUTPUT_METRIC_CHOICES,
        required=False,
    )

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs and kwargs['instance']:
            initial = kwargs.get('initial', {})
            instance = kwargs['instance']
            if len(instance.output_metrics):
                if len(instance.output_metrics) >= 1:
                    initial['output_metric_1'] = instance.output_metrics[0]
                if len(instance.output_metrics) >= 2:
                    initial['output_metric_2'] = instance.output_metrics[1]
            kwargs.update({'initial': initial})
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = self.cleaned_data
        output_metrics = []
        output_metric_1 = cleaned_data.pop('output_metric_1')
        if output_metric_1:
            output_metrics.append(output_metric_1)
        output_metric_2 = cleaned_data.pop('output_metric_2')
        if output_metric_2:
            output_metrics.append(output_metric_2)
        self.instance.output_metrics = output_metrics
        return cleaned_data

    class Meta:
        fields = [
            'name',
            'description',
            'icon',
            'group',
            'output_metric_1',
            'output_metric_2',
            'show_in_menu',
        ]
        fieldsets = (
            (_('Analysis'), {
                'fields': (
                    'name',
                    'description',
                    'icon',
                    'output_metric_1',
                    'output_metric_2',
                ),
            }),
            (_('Program Design Lessons'), {
                'fields': (
                    'group',
                    'show_in_menu',
                ),
            }),
        )
        help_texts = {
            'group': _("Select the group for this activity in the Program Design Lessons menu."),
        }

website/forms/core.py
from django.utils.html import mark_safe
from django.utils.translation import gettext as _
from ombucore.htmloutput_field import HtmlOutputField
from ombucore.admin.forms.base import ModelFormBase


class SectorCategoryMappingForm(ModelFormBase):
    criteria_text = HtmlOutputField(
        label='',
        render_fn=lambda *ars, **kwargs: mark_safe('<h2>{}</h2>'.format(_('Criteria'))),
        required=False,
    )
    result_text = HtmlOutputField(
        label='',
        render_fn=lambda *ars, **kwargs: mark_safe('<h2>{}</h2>'.format(_('Result'))),
        required=False,
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        if not cleaned_data['sector'] and not cleaned_data['category']:
            self.add_error('category', _('Please select a sector, category, or both'))
        return cleaned_data

    class Meta:
        fields = [
            'criteria_text',
            'country_code',
            'grant_code',
            'budget_line_code',
            'account_code',
            'site_code',
            'sector_code',
            'budget_line_description',
            'result_text',
            'sector',
            'category',
        ]

website/forms/fields.py
from decimal import Decimal

from django import forms
from django.core.exceptions import ValidationError


class FixedDecimalField(forms.DecimalField):

    def __init__(self, *args, **kwargs):
        self.quantize = kwargs.pop('quantize', '0.01')
        if not 'decimal_places' in kwargs:
            kwargs['decimal_places'] = 2
        super().__init__(*args, **kwargs)

    def prepare_value(self, value):
        if value:
            if not isinstance(value, Decimal):
                value = Decimal(value)
            if self.quantize:
                value = value.quantize(Decimal(self.quantize))
        return value

    def to_python(self, value):
        super().to_python(value)
        if value:
            if not isinstance(value, Decimal):
                value = Decimal(value)
            if self.quantize:
                value = value.quantize(Decimal(self.quantize))
        return value


class PositiveFixedDecimalField(FixedDecimalField):
    def validate(self, value):
        super().validate(value)
        if isinstance(value, Decimal) and value <= 0:
            raise ValidationError("This field is required and must be greater than zero.", code='invalid')


class CalculatedFixedDecimalField(FixedDecimalField):
    def __init__(self, *args, **kwargs):
        kwargs['required'] = False
        kwargs['disabled'] = True
        super().__init__(*args, **kwargs)

website/templates/analysis/analysis-table/_analysis-table-edit-note.html
{% load help panels_form_extras i18n humanize %}
<tr class="analysis-table__edit-row allocate-costs">
      <td colspan="{% if showSectorCode == 'true' %}7{% elif type == 'categorizeSector' %}8{% else %}6{% endif %}" class="analysis-table__edit-row-cell">
            <form action="{% url 'api--costlineitem--add-note' pk=cost_line_item.id %}" method="POST" novalidate data-show-loading-on-submit>
              {% csrf_token %}
                  <table class="analysis-table__edit-table">
                    <tbody>
                        <tr>
                            <td class="analysis-table__edit-sector-cell">                           
                            </td>
                            <td class="analysis-table__edit-category-cell analysis-table__edit-category-cell--note">
                                <label for="id_category" class="analysis-table__edit-row-label">{% trans 'Note' %}</label>
                                <textarea name="note" class="analysis-table__edit-note-input">{{ cost_line_item.note }}</textarea>
                                <div class="form__help-text">Provide a note explaining how you arrived at the allocation percent for this cost line item</div>
                            </td>
                            <td class="analysis-table__edit-actions-cell">
                                <button class="analysis-table__edit-action analysis-table__edit-action--save" type="submit" data-object-id="{{ cost_line_item.id }}" data-endpoint="{% url 'api--costlineitem--add-note' pk=cost_line_item.id %}" name="action" value="save_cost_line_item_config">{% trans 'Save' %}</button>
                                <button class="analysis-table__edit-action analysis-table__edit-action--cancel" type="submit" name="action" value="cancel">{% trans 'Cancel' %}</button>
                            </td>
                        </tr>
                    </tbody>
              </table>
            </form>
      </td>
</tr>

website/templates/analysis/analysis-table/_analysis-table-edit-row.html
{% load help panels_form_extras i18n humanize %}
<tr class="analysis-table__edit-row confirm-categories">
      <td colspan="{% if showSectorCode == 'true' %}7{% elif type == 'categorizeSector' %}8{% else %}6{% endif %}" class="analysis-table__edit-row-cell">
            <form action="{{request.path}}" method="POST" novalidate data-show-loading-on-submit
                  data-initial-category_id="{{ cost_line_item.config.category_id }}"
                  data-initial-sector_id="{{ cost_line_item.config.sector_id }}" >
              {% csrf_token %}
                  <input type="hidden" name="config_id" value="{{cost_line_item.config.id}}" /> 
                  <table class="analysis-table__edit-table">
                    <tbody>
                        <tr>
                            <td class="analysis-table__edit-sector-cell">
                                <label for="id_sector-{{cost_line_item.config.id}}" class="analysis-table__edit-row-label">{% trans 'Sector' %}</label>
                                <select name="sector_id" id="id_sector-{{cost_line_item.config.id}}" class="analysis-table__edit-row-select">
                                    {% for sector_id, sector_name in sector_choices %}
                                        <option value="{{sector_id}}" {% if sector_id == cost_line_item.config.sector_id %}selected{% endif %}>{{sector_name}}</option>
                                    {% endfor %}
                                </select>                              
                            </td>
                            <td class="analysis-table__edit-category-cell">
                                <label for="id_category-{{cost_line_item.config.id}}" class="analysis-table__edit-row-label">{% trans 'Category' %}</label>
                                <select name="category_id" id="id_category-{{cost_line_item.config.id}}" class="analysis-table__edit-row-select">
                                    {% for category_id, category_name in category_choices %}
                                        <option value="{{category_id}}" {% if category_id == cost_line_item.config.category_id %}selected{% endif %}>{{category_name}}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td class="analysis-table__edit-actions-cell">
                                <button class="analysis-table__edit-action analysis-table__edit-action--save" data-object-id="{{ cost_line_item.id }}" data-endpoint="{% url 'api--costlineitem--edit-sector-category' pk=cost_line_item.id %}" type="submit" name="action" value="save_cost_line_item_config">{% trans 'Save' %}</button>
                                <button class="analysis-table__edit-action analysis-table__edit-action--cancel" type="submit" name="action" value="cancel">{% trans 'Cancel' %}</button>
                            </td>
                        </tr>
                    </tbody>
              </table>
            </form>
      </td>
</tr>

website/templates/analysis/analysis-table/_analysis-table-header-toggle.html
{% load i18n %}
<button class="analysis-table__category-toggle" aria-label="{% trans 'Toggle Category' %}"></button>
<div class="analysis-table__category-toggle-icon-wrapper"><span class="analysis-table__category-toggle-icon analysis-table__category-toggle-icon--expand">{% include 'icons/plus.svg' %}</span><span class="analysis-table__category-toggle-icon analysis-table__category-toggle-icon--collapse">{% include 'icons/minus.svg' %}</span>
</div>

website/templates/analysis/analysis-table/_analysis-table-transaction-rows-content.html
{% load help humanize analysis website_tags %}
{% for transaction in transactions %}
    <tr>
    {% with sensitive_data=account_code_descriptions|dict_get:transaction.account_code|attr:'sensitive_data' %}
        <td class="analysis-table__cost-item-cell analysis-table__transaction-table-summary">{{transaction.transaction_description}}</td>
        <td class="analysis-table__site-cell">{{transaction.site_code}}</td>
        <td class="analysis-table__description-cell">{{transaction.date}}</td>
        <td class="analysis-table__amount-cell">{% if not sensitive_data %}{{transaction.amount_in_instance_currency|format_currency:transaction.analysis.currency_code}}{% endif %}</td>
        <td {% if type == 'fixData' %}colspan="3"{% endif %} class="analysis-table__edit-cell"></td>
    {% endwith %}
    </tr>
{% endfor %}

website/templates/analysis/analysis-table/_analysis-table-transaction-rows.html
{% load help panels_form_extras i18n humanize website_tags %}
{% if dioptra_settings.show_transactions %}
    {% if transactions_count > 0 %}
        <tr class="analysis-table__transaction-row">
            <td colspan="{% if type == 'fixData' %}8{% elif type == 'categorizeSector' %}8{% else %}7{% endif %}" class="analysis-table__transaction-cell">
                <div class="analysis-table__transactions-detail">
                    <table class="analysis-table__transaction-table{% if showSectorCode == 'true' %} analysis-table__transaction-table--with-sector-code{% endif %}">
                        <thead>
                        <tr>
                            <th class="analysis-table__transaction-table-summary">{% blocktrans %}{{ transactions_count }} Transactions{% endblocktrans %}</th>
                            <th>{{ 'Site'|label_override:'tr_site_code' }}</th>
                            <th>{{ 'Date'|label_override:'tr_date' }}</th>
                            <th class="analysis-table__amount-cell">{{ 'Amount'|label_override:'tr_amount' }}</th>
                            <th {% if type == 'fixData' %}colspan="3"{% elif type == 'categorizeSector' %}colspan="3"{% endif %}></th>
                        </tr>
                        </thead>
                        <tbody data-cost-line-item-transactions="{{ cost_line_item.id }}">
                        <tr>
                            <td class="analysis-table__cost-item-cell analysis-table__transaction-table-summary">{% trans "Loading..." %}</td>
                            <td class="analysis-table__site-cell"></td>
                            <td class="analysis-table__description-cell"></td>
                            <td class="analysis-table__amount-cell"></td>
                            <td {% if type == 'fixData' %}colspan="3"{% elif type == 'categorizeSector' %}colspan="3"{% endif %} class="analysis-table__edit-cell"></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
    {% endif %}
{% endif %}